import { useMemo, useState } from 'react'
import {
  Activity, Archive, Bell, CalendarDays, CheckCircle2, ChevronRight, ClipboardList,
  Clock3, CreditCard, FileArchive, FileText, FolderKanban, LayoutDashboard, Mail,
  Menu, Plus, Search, Settings2, Users, X, Euro, AlertTriangle, MapPin, Phone,
  MoreHorizontal, Trash2, Pencil, Check, BriefcaseBusiness, Building2, Send,
} from 'lucide-react'
import { useAppStore } from '@/store/appStore'
import { getEncaisse } from '@/lib/utils'
import { computeStatus } from '@/lib/status'

const nav = [
  ['dashboard','Tableau de bord',LayoutDashboard], ['dossiers','Dossiers',FolderKanban],
  ['clients','Clients',Users], ['agenda','Agenda',CalendarDays], ['taches','Tâches',ClipboardList],
  ['documents','Documents',FileArchive], ['facturation','Facturation',CreditCard],
  ['courriers','Courriers',Mail], ['administrations','Administrations',Building2],
  ['rapports','Rapports',Activity], ['parametres','Paramètres',Settings2],
] as const

type Module = typeof nav[number][0]
type Client = { id:number; nom:string; type:'Particulier'|'Professionnel'; telephone:string; email:string; adresse:string; notes:string }
type Task = { id:number; titre:string; dossier:string; responsable:string; echeance:string; priorite:'Haute'|'Normale'|'Basse'; faite:boolean }
type Letter = { id:number; objet:string; destinataire:string; statut:'Brouillon'|'Envoyé'; date:string }

const seedClients: Client[] = [
  {id:1,nom:'Client exemple',type:'Particulier',telephone:'0550 00 00 00',email:'client@email.com',adresse:'Oran',notes:''},
  {id:2,nom:'Entreprise Atlas',type:'Professionnel',telephone:'041 00 00 00',email:'contact@atlas.dz',adresse:'Es Sénia, Oran',notes:'Dossiers fonciers récurrents'},
]
const seedTasks: Task[] = [
  {id:1,titre:'Relancer les pièces manquantes',dossier:'DOS-2026-014',responsable:'Secrétariat',echeance:'2026-09-11',priorite:'Haute',faite:false},
  {id:2,titre:'Préparer dépôt cadastral',dossier:'DOS-2026-009',responsable:'Cabinet',echeance:'2026-09-14',priorite:'Normale',faite:false},
  {id:3,titre:'Classer dossier terminé',dossier:'DOS-2026-003',responsable:'Secrétariat',echeance:'2026-09-09',priorite:'Basse',faite:true},
]
const seedLetters: Letter[] = [
  {id:1,objet:'Demande de pièces complémentaires',destinataire:'Client exemple',statut:'Brouillon',date:'2026-09-10'},
  {id:2,objet:'Lettre de dépôt cadastral',destinataire:'Conservation foncière',statut:'Envoyé',date:'2026-09-08'},
]

function money(n:number){ return new Intl.NumberFormat('fr-DZ',{minimumFractionDigits:2,maximumFractionDigits:2}).format(n)+' DA' }
function dateFr(s?:string){ if(!s)return '—'; const d=new Date(s+'T00:00:00'); return d.toLocaleDateString('fr-FR',{day:'2-digit',month:'2-digit',year:'numeric'}) }

export default function OfficePage(){
  const { dossiers, setModalOpen, setEditingDossierId, theme, toggleTheme } = useAppStore()
  const [module,setModule]=useState<Module>('dashboard')
  const [query,setQuery]=useState('')
  const [clients,setClients]=useState(seedClients)
  const [tasks,setTasks]=useState(seedTasks)
  const [letters,setLetters]=useState(seedLetters)
  const [showNewClient,setShowNewClient]=useState(false)
  const [showNewTask,setShowNewTask]=useState(false)
  const [clientForm,setClientForm]=useState({nom:'',type:'Particulier' as Client['type'],telephone:'',email:'',adresse:'',notes:''})
  const [taskForm,setTaskForm]=useState({titre:'',dossier:'',responsable:'Secrétariat',echeance:'',priorite:'Normale' as Task['priorite']})

  const activeDossiers=dossiers.filter(d=>!d.archived&&!d.in_trash)
  const stats=useMemo(()=>({
    total:activeDossiers.length,
    retard:activeDossiers.filter(d=>computeStatus(d,getEncaisse(d))==='En retard').length,
    termine:activeDossiers.filter(d=>computeStatus(d,getEncaisse(d))==='Termine').length,
    montant:activeDossiers.reduce((s,d)=>s+d.montant,0),
    encaisse:activeDossiers.reduce((s,d)=>s+getEncaisse(d),0),
    reste:activeDossiers.reduce((s,d)=>s+Math.max(0,d.montant-getEncaisse(d)),0),
  }),[activeDossiers])
  const filteredDossiers=activeDossiers.filter(d=>[d.id,d.nom,d.endroit,d.telephone,d.observations].join(' ').toLowerCase().includes(query.toLowerCase()))

  const addClient=()=>{ if(!clientForm.nom.trim())return; setClients(v=>[{id:Date.now(),...clientForm},...v]); setClientForm({nom:'',type:'Particulier',telephone:'',email:'',adresse:'',notes:''}); setShowNewClient(false) }
  const addTask=()=>{ if(!taskForm.titre.trim())return; setTasks(v=>[{id:Date.now(),...taskForm,faite:false},...v]); setTaskForm({titre:'',dossier:'',responsable:'Secrétariat',echeance:'',priorite:'Normale'}); setShowNewTask(false) }

  return <div className={`office-shell ${theme}`}>
    <aside className="office-sidebar">
      <div className="brand"><div className="brand-mark">G</div><div><strong>GEOMAN</strong><small>Gestion foncière</small></div></div>
      <div className="office-label">ESPACE CABINET</div>
      <nav>{nav.map(([id,label,Icon])=><button key={id} className={module===id?'active':''} onClick={()=>setModule(id as Module)}><Icon size={17}/><span>{label}</span>{id==='taches'&&tasks.filter(t=>!t.faite).length>0&&<b>{tasks.filter(t=>!t.faite).length}</b>}</button>)}</nav>
      <div className="sidebar-bottom"><div className="cabinet-card"><BriefcaseBusiness size={18}/><div><strong>Cabinet</strong><span>Géomètre-expert foncier</span></div></div><button onClick={toggleTheme}><span>{theme==='dark'?'☀':'☾'}</span>{theme==='dark'?'Mode clair':'Mode sombre'}</button></div>
    </aside>
    <main className="office-main">
      <header className="office-header"><button className="mobile-menu"><Menu size={20}/></button><div><div className="breadcrumb">Cabinet <ChevronRight size={13}/> {nav.find(n=>n[0]===module)?.[1]}</div><h1>{nav.find(n=>n[0]===module)?.[1]}</h1></div><div className="header-actions"><div className="global-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher un dossier, client…"/></div><button className="icon-btn"><Bell size={18}/><i/></button><div className="avatar">SE</div></div></header>
      <div className="office-content">
        {module==='dashboard'&&<Dashboard stats={stats} tasks={tasks} dossiers={activeDossiers} onOpenDossier={(id)=>{setEditingDossierId(id);setModalOpen('edit-dossier')}} setModule={setModule}/>} 
        {module==='dossiers'&&<Dossiers dossiers={filteredDossiers} query={query} onNew={()=>setModalOpen('new-dossier')} onOpen={(id)=>{setEditingDossierId(id);setModalOpen('edit-dossier')}}/>}
        {module==='clients'&&<Clients clients={clients} query={query} onNew={()=>setShowNewClient(true)} onDelete={id=>setClients(v=>v.filter(c=>c.id!==id))}/>} 
        {module==='agenda'&&<Agenda tasks={tasks} setModule={setModule}/>} 
        {module==='taches'&&<Tasks tasks={tasks} onNew={()=>setShowNewTask(true)} onToggle={id=>setTasks(v=>v.map(t=>t.id===id?{...t,faite:!t.faite}:t))}/>} 
        {module==='documents'&&<Documents dossiers={activeDossiers}/>} 
        {module==='facturation'&&<Billing stats={stats} dossiers={activeDossiers}/>} 
        {module==='courriers'&&<Letters letters={letters} onNew={()=>setLetters(v=>[{id:Date.now(),objet:'Nouveau courrier',destinataire:'',statut:'Brouillon',date:new Date().toISOString().slice(0,10)},...v])}/>} 
        {module==='administrations'&&<Administrations/>}
        {module==='rapports'&&<Reports stats={stats} dossiers={activeDossiers}/>} 
        {module==='parametres'&&<Settings/>}
      </div>
    </main>
    {showNewClient&&<Modal title="Nouveau client" onClose={()=>setShowNewClient(false)}><div className="form-grid">{[['Nom / raison sociale','nom'],['Téléphone','telephone'],['E-mail','email'],['Adresse','adresse']].map(([l,k])=><label key={k}>{l}<input value={(clientForm as any)[k]} onChange={e=>setClientForm({...clientForm,[k]:e.target.value})}/></label>)}<label>Type<select value={clientForm.type} onChange={e=>setClientForm({...clientForm,type:e.target.value as Client['type']})}><option>Particulier</option><option>Professionnel</option></select></label><label>Notes<textarea value={clientForm.notes} onChange={e=>setClientForm({...clientForm,notes:e.target.value})}/></label></div><div className="modal-actions"><button onClick={()=>setShowNewClient(false)}>Annuler</button><button className="primary" onClick={addClient}><Check size={15}/>Créer le client</button></div></Modal>}
    {showNewTask&&<Modal title="Nouvelle tâche" onClose={()=>setShowNewTask(false)}><div className="form-grid">{[['Intitulé','titre'],['Dossier','dossier']].map(([l,k])=><label key={k}>{l}<input value={(taskForm as any)[k]} onChange={e=>setTaskForm({...taskForm,[k]:e.target.value})}/></label>)}<label>Responsable<select value={taskForm.responsable} onChange={e=>setTaskForm({...taskForm,responsable:e.target.value})}><option>Secrétariat</option><option>Géomètre</option><option>Cabinet</option></select></label><label>Échéance<input type="date" value={taskForm.echeance} onChange={e=>setTaskForm({...taskForm,echeance:e.target.value})}/></label><label>Priorité<select value={taskForm.priorite} onChange={e=>setTaskForm({...taskForm,priorite:e.target.value as Task['priorite']})}><option>Haute</option><option>Normale</option><option>Basse</option></select></label></div><div className="modal-actions"><button onClick={()=>setShowNewTask(false)}>Annuler</button><button className="primary" onClick={addTask}><Check size={15}/>Créer la tâche</button></div></Modal>}
  </div>
}

function Dashboard({stats,tasks,dossiers,onOpenDossier,setModule}:{stats:any;tasks:Task[];dossiers:any[];onOpenDossier:(id:string)=>void;setModule:(m:Module)=>void}){
 const urgent=tasks.filter(t=>!t.faite).sort((a,b)=>a.echeance.localeCompare(b.echeance)).slice(0,4)
 return <><div className="welcome"><div><p className="eyebrow">VUE D’ENSEMBLE</p><h2>Bonjour, Secrétariat 👋</h2><p>Voici l’activité du cabinet et les éléments qui nécessitent votre attention.</p></div><button className="primary" onClick={()=>setModule('dossiers')}><Plus size={17}/> Nouveau dossier</button></div>
 <div className="kpi-grid"><Kpi icon={FolderKanban} label="Dossiers actifs" value={stats.total}/><Kpi icon={AlertTriangle} label="En retard" value={stats.retard} danger/><Kpi icon={Euro} label="Reste à encaisser" value={money(stats.reste)}/><Kpi icon={CheckCircle2} label="Dossiers terminés" value={stats.termine}/></div>
 <div className="dashboard-grid"><section className="panel wide"><PanelTitle title="Dossiers à surveiller" action="Voir tous" onClick={()=>setModule('dossiers')}/><div className="table-wrap"><table><thead><tr><th>Dossier</th><th>Client</th><th>Localisation</th><th>Échéance</th><th>État</th><th>Reste</th></tr></thead><tbody>{dossiers.slice(0,6).map(d=><tr key={d.id} onClick={()=>onOpenDossier(d.id)}><td className="mono">{d.id}</td><td><strong>{d.nom}</strong></td><td><MapPin size={13}/> {d.endroit||'—'}</td><td>{dateFr(d.date_finale)}</td><td><Status value={computeStatus(d,getEncaisse(d))}/></td><td>{money(Math.max(0,d.montant-getEncaisse(d)))}</td></tr>)}{dossiers.length===0&&<Empty text="Aucun dossier actif"/>}</tbody></table></div></section><section className="panel"><PanelTitle title="Tâches prioritaires" action="Agenda" onClick={()=>setModule('taches')}/>{urgent.map(t=><div className="task-line" key={t.id}><div className={`task-dot ${t.priorite.toLowerCase()}`}/><div><strong>{t.titre}</strong><span>{t.dossier||'Sans dossier'} · {dateFr(t.echeance)}</span></div></div>)}{urgent.length===0&&<Empty text="Tout est à jour"/>}</section></div>
 <div className="dashboard-grid"><section className="panel"><PanelTitle title="Encaissements"/><div className="big-number">{money(stats.encaisse)}</div><p className="muted">sur {money(stats.montant)} facturés</p><div className="progress"><span style={{width:`${stats.montant?Math.min(100,stats.encaisse/stats.montant*100):0}%`}}/></div></section><section className="panel"><PanelTitle title="Raccourcis"/><div className="quick-grid"><button onClick={()=>setModule('clients')}><Users/>Nouveau client</button><button onClick={()=>setModule('courriers')}><Mail/>Courrier</button><button onClick={()=>setModule('agenda')}><CalendarDays/>Agenda</button><button onClick={()=>setModule('documents')}><FileArchive/>Documents</button></div></section></div></>
}
function Dossiers({dossiers,onNew,onOpen}:{dossiers:any[];query:string;onNew:()=>void;onOpen:(id:string)=>void}){return <><div className="page-head"><div><p className="eyebrow">GESTION FONCIÈRE</p><h2>Portefeuille de dossiers</h2><p className="muted">Suivez les missions, échéances, dépôts et règlements.</p></div><button className="primary" onClick={onNew}><Plus size={17}/> Nouveau dossier</button></div><div className="toolbar"><div className="filter-pill active">Actifs <b>{dossiers.length}</b></div><div className="filter-pill">En retard</div><div className="filter-pill">Impayés</div><div className="spacer"/><button className="secondary"><FileText size={15}/> Exporter</button></div><section className="panel"><div className="table-wrap"><table><thead><tr><th>Dossier</th><th>Client</th><th>Endroit</th><th>Échéance</th><th>Mission</th><th>Dépôt CAD</th><th>Montant</th><th>État</th><th/></tr></thead><tbody>{dossiers.map(d=><tr key={d.id} onClick={()=>onOpen(d.id)}><td className="mono">{d.id}</td><td><strong>{d.nom}</strong><small>{d.telephone||'Téléphone non renseigné'}</small></td><td>{d.endroit||'—'}</td><td>{dateFr(d.date_finale)}</td><td><Tag>{d.regul?'Régularisation':d.acte?'Acte':'Mission foncière'}</Tag></td><td><Status value={d.depot_cad||'Non déposé'}/></td><td><strong>{money(d.montant)}</strong><small>Reste {money(Math.max(0,d.montant-getEncaisse(d)))}</small></td><td><Status value={computeStatus(d,getEncaisse(d))}/></td><td><MoreHorizontal size={17}/></td></tr>)}{dossiers.length===0&&<Empty text="Aucun dossier correspondant"/>}</tbody></table></div></section></>}
function Clients({clients,onNew,onDelete}:{clients:Client[];query:string;onNew:()=>void;onDelete:(id:number)=>void}){return <><div className="page-head"><div><p className="eyebrow">RELATION CLIENT</p><h2>Clients</h2><p className="muted">Fiche 360° des particuliers, entreprises et mandants.</p></div><button className="primary" onClick={onNew}><Plus size={17}/> Nouveau client</button></div><div className="client-grid">{clients.map(c=><article className="client-card" key={c.id}><div className="client-top"><div className="client-avatar">{c.nom.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase()}</div><div><strong>{c.nom}</strong><span>{c.type}</span></div><button className="ghost"><MoreHorizontal size={17}/></button></div><div className="client-info"><span><Phone size={14}/>{c.telephone||'—'}</span><span><Mail size={14}/>{c.email||'—'}</span><span><MapPin size={14}/>{c.adresse||'—'}</span></div><div className="client-footer"><span>Client #{String(c.id).padStart(4,'0')}</span><button className="danger-text" onClick={()=>onDelete(c.id)}><Trash2 size={14}/>Supprimer</button></div></article>)}</div></>}
function Agenda({tasks,setModule}:{tasks:Task[];setModule:(m:Module)=>void}){const days=['Lun 07','Mar 08','Mer 09','Jeu 10','Ven 11'];return <><div className="page-head"><div><p className="eyebrow">ORGANISATION</p><h2>Agenda du cabinet</h2><p className="muted">Rendez-vous, échéances et rappels centralisés.</p></div><button className="primary" onClick={()=>setModule('taches')}><Plus size={17}/> Ajouter un événement</button></div><section className="panel calendar"><div className="calendar-head"><button>‹</button><strong>Septembre 2026</strong><button>›</button><span/><button className="secondary">Aujourd’hui</button></div><div className="calendar-grid">{days.map(d=><div className="day" key={d}><strong>{d}</strong><div className="event blue">08:30 · Réunion cabinet</div>{d==='Jeu 10'&&<div className="event amber">15:00 · Relance dossier</div>}{d==='Ven 11'&&tasks.filter(t=>!t.faite).slice(0,1).map(t=><div className="event red" key={t.id}>Échéance · {t.titre}</div>)}</div>)}</div></section></>}
function Tasks({tasks,onNew,onToggle}:{tasks:Task[];onNew:()=>void;onToggle:(id:number)=>void}){return <><div className="page-head"><div><p className="eyebrow">WORKFLOW</p><h2>Tâches & relances</h2><p className="muted">Ne laissez plus une échéance ou une pièce manquante passer.</p></div><button className="primary" onClick={onNew}><Plus size={17}/> Nouvelle tâche</button></div><section className="panel"><div className="task-table">{tasks.map(t=><div className={`task-row ${t.faite?'done':''}`} key={t.id}><button className="check" onClick={()=>onToggle(t.id)}>{t.faite&&<Check size={14}/>}</button><div className="task-main"><strong>{t.titre}</strong><span>{t.dossier||'Sans dossier'} · {t.responsable}</span></div><Tag>{t.priorite}</Tag><span className="task-date"><Clock3 size={14}/>{dateFr(t.echeance)}</span><button className="ghost"><Pencil size={15}/></button></div>)}</div></section></>}
function Documents({dossiers}:{dossiers:any[]}){return <><div className="page-head"><div><p className="eyebrow">ARCHIVAGE</p><h2>Documents</h2><p className="muted">Classement numérique par dossier, avec historique et recherche.</p></div><button className="primary"><Plus size={17}/> Importer des documents</button></div><div className="folder-grid"><Folder title="Dossiers en cours" count={dossiers.length}/><Folder title="Actes & titres" count={dossiers.filter(d=>d.acte).length}/><Folder title="Dépôts cadastraux" count={dossiers.filter(d=>d.depot_cad&&d.depot_cad!=='').length}/><Folder title="Courriers" count={seedLetters.length}/></div><section className="panel"><PanelTitle title="Activité documentaire"/><div className="activity"><div><FileText/><span><strong>Demande de pièces complémentaires</strong><small>Courrier · il y a 2 h</small></span></div><div><FileArchive/><span><strong>Plan cadastral.pdf</strong><small>DOS-2026-009 · hier</small></span></div><div><FileText/><span><strong>Acte de propriété</strong><small>DOS-2026-003 · 08/09/2026</small></span></div></div></section></>}
function Billing({stats,dossiers}:{stats:any;dossiers:any[]}){return <><div className="page-head"><div><p className="eyebrow">FINANCES</p><h2>Facturation & paiements</h2><p className="muted">Pilotage des honoraires, règlements et soldes clients.</p></div><button className="primary"><Plus size={17}/> Nouveau paiement</button></div><div className="kpi-grid"><Kpi icon={Euro} label="Total facturé" value={money(stats.montant)}/><Kpi icon={CheckCircle2} label="Encaissé" value={money(stats.encaisse)}/><Kpi icon={Clock3} label="À encaisser" value={money(stats.reste)} danger/></div><section className="panel"><PanelTitle title="Situation par dossier"/><div className="table-wrap"><table><thead><tr><th>Dossier</th><th>Client</th><th>Facturé</th><th>Encaissé</th><th>Solde</th><th>Progression</th></tr></thead><tbody>{dossiers.map(d=>{const e=getEncaisse(d),r=Math.max(0,d.montant-e);return <tr key={d.id}><td className="mono">{d.id}</td><td>{d.nom}</td><td>{money(d.montant)}</td><td>{money(e)}</td><td><strong>{money(r)}</strong></td><td><div className="mini-progress"><span style={{width:`${d.montant?Math.min(100,e/d.montant*100):0}%`}}/></div></td></tr>})}</tbody></table></div></section></>}
function Letters({letters,onNew}:{letters:Letter[];onNew:()=>void}){return <><div className="page-head"><div><p className="eyebrow">CORRESPONDANCE</p><h2>Courriers</h2><p className="muted">Modèles, publipostage, envoi et suivi des correspondances.</p></div><button className="primary" onClick={onNew}><Plus size={17}/> Nouveau courrier</button></div><div className="template-grid"><button><FileText/><strong>Demande de pièces complémentaires</strong><span>Modèle</span></button><button><FileText/><strong>Convocation client</strong><span>Modèle</span></button><button><FileText/><strong>Lettre de dépôt cadastral</strong><span>Modèle</span></button></div><section className="panel"><PanelTitle title="Courriers récents"/><div className="table-wrap"><table><thead><tr><th>Objet</th><th>Destinataire</th><th>Date</th><th>Statut</th><th/></tr></thead><tbody>{letters.map(l=><tr key={l.id}><td><strong>{l.objet}</strong></td><td>{l.destinataire||'—'}</td><td>{dateFr(l.date)}</td><td><Status value={l.statut}/></td><td><button className="secondary"><Send size={14}/> Ouvrir</button></td></tr>)}</tbody></table></div></section></>}
function Administrations(){const rows=[['Cadastre','Dépôts et suivi des dossiers cadastraux','8 dossiers en cours'],['Conservation foncière','Actes, titres et demandes','4 dossiers en attente'],['Domaines','Dépôts et régularisations','3 dossiers en cours'],['APC / Services techniques','Correspondances et demandes','2 relances']];return <><div className="page-head"><div><p className="eyebrow">PARTENAIRES PUBLICS</p><h2>Administrations</h2><p className="muted">Contacts, dépôts, échéances et historique par administration.</p></div><button className="primary"><Plus size={17}/> Ajouter un contact</button></div><div className="admin-grid">{rows.map(([n,d,s])=><article key={n} className="admin-card"><div className="admin-icon"><Building2 size={20}/></div><div><strong>{n}</strong><p>{d}</p><span>{s}</span></div><ChevronRight/></article>)}</div></>}
function Reports({stats,dossiers}:{stats:any;dossiers:any[]}){const locations=Object.entries(dossiers.reduce((a:any,d:any)=>{const k=d.endroit||'Non renseigné';a[k]=(a[k]||0)+1;return a},{})).sort((a:any,b:any)=>b[1]-a[1]).slice(0,6);return <><div className="page-head"><div><p className="eyebrow">ANALYSE</p><h2>Rapports</h2><p className="muted">Indicateurs opérationnels du cabinet.</p></div><button className="secondary"><FileText size={15}/> Exporter le rapport</button></div><div className="report-grid"><section className="panel"><PanelTitle title="Répartition par localisation"/>{locations.map(([n,v]:any)=><div className="bar-row" key={n}><span>{n}</span><div><i style={{width:`${Math.max(8,v/Math.max(1,locations[0]?.[1])*100)}%`}}/></div><b>{v}</b></div>)}{locations.length===0&&<Empty text="Pas encore de données"/>}</section><section className="panel"><PanelTitle title="Indicateurs"/><div className="report-stat"><span>Dossiers actifs</span><strong>{stats.total}</strong></div><div className="report-stat"><span>Taux d’encaissement</span><strong>{stats.montant?Math.round(stats.encaisse/stats.montant*100):0}%</strong></div><div className="report-stat"><span>Retards</span><strong>{stats.retard}</strong></div><div className="report-stat"><span>Terminés</span><strong>{stats.termine}</strong></div></section></div></>}
function Settings(){return <><div className="page-head"><div><p className="eyebrow">CONFIGURATION</p><h2>Paramètres du cabinet</h2><p className="muted">Personnalisez les règles, modèles et préférences de travail.</p></div><button className="primary"><Check size={16}/> Enregistrer</button></div><div className="settings-grid"><section className="panel"><PanelTitle title="Identité du cabinet"/><div className="form-grid"><label>Nom du cabinet<input defaultValue="Cabinet de géomètre-expert foncier"/></label><label>Téléphone<input placeholder="Téléphone"/></label><label>E-mail<input placeholder="cabinet@email.dz"/></label><label>Adresse<textarea placeholder="Adresse du cabinet"/></label></div></section><section className="panel"><PanelTitle title="Workflow"/><SettingRow title="Rappels automatiques" text="Alerter avant les échéances importantes"/><SettingRow title="Confirmation avant suppression" text="Éviter les suppressions accidentelles"/><SettingRow title="Journal d’activité" text="Conserver les actions des utilisateurs"/></section><section className="panel"><PanelTitle title="Numérotation"/><div className="form-grid"><label>Préfixe dossiers<input defaultValue="DOS"/></label><label>Prochaine référence<input defaultValue="2026-015"/></label><label>Devise<select defaultValue="DZD"><option>DZD — Dinar algérien</option><option>EUR — Euro</option></select></label></div></section></div></>}

function Kpi({icon:Icon,label,value,danger}:{icon:any;label:string;value:any;danger?:boolean}){return <div className="kpi"><div className={`kpi-icon ${danger?'danger':''}`}><Icon size={18}/></div><div><span>{label}</span><strong>{value}</strong></div></div>}
function PanelTitle({title,action,onClick}:{title:string;action?:string;onClick?:()=>void}){return <div className="panel-title"><h3>{title}</h3>{action&&<button onClick={onClick}>{action}<ChevronRight size={14}/></button>}</div>}
function Status({value}:{value:string}){const v=value||'—';let cls='neutral';if(/retard|impay|attente/i.test(v))cls='red';else if(/proche|partiel|brouillon/i.test(v))cls='amber';else if(/termin|envoy|depose|déposé/i.test(v))cls='green';return <span className={`status ${cls}`}><i/>{v}</span>}
function Tag({children}:{children:React.ReactNode}){return <span className="tag">{children}</span>}
function Folder({title,count}:{title:string;count:number}){return <div className="folder"><div><FileArchive size={22}/></div><strong>{title}</strong><span>{count} élément{count>1?'s':''}</span></div>}
function SettingRow({title,text}:{title:string;text:string}){const [on,setOn]=useState(true);return <div className="setting-row"><div><strong>{title}</strong><span>{text}</span></div><button className={`switch ${on?'on':''}`} onClick={()=>setOn(!on)}><i/></button></div>}
function Empty({text}:{text:string}){return <tr><td colSpan={9}><div className="empty"><FileText size={22}/><span>{text}</span></div></td></tr>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><h3>{title}</h3><button onClick={onClose}><X size={18}/></button></div>{children}</div></div>}
